### ISSUE TITLE
Feature: Search

### ISSUE THREAD

**Issue by tobinstultiens** [tobinstultiens/Recipe-manager-API#1]
### Description
As a user, I want to search for recipes, So that it's easy to find recipes.

### Acceptance Criteria
Reference: [Done-Done Checklist](https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] Should be able to find a recipe on the basis of the ingredients.
- [ ] Should be able to find a recipe by using their tags.
- [ ] Should be able to find a recipe by their category.
- [ ] Should be able to use it to filter for recipes you can make based on the ingredients you have.

Also, here are a few points that need to be addressed:

1. Constraint 1: _TBA_

### Tasks
- [ ] _TBA_
