### ISSUE TITLE
Feature: Recipes

### ISSUE THREAD

**Issue by tobinstultiens** [tobinstultiens/Recipe-manager-API#10]
### Description
As a user, I'd like to manage recipes, in order to store them, so I can use them.

### Acceptance Criteria
Reference: [Done-Done Checklist](https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [x] Should be able to create a recipe.
- [x] Should be able to edit a recipe.
- [x] Should be able to remove a recipe.
- [x] Should be able to link a video tutorial.
- [x] Should be able to add ingredients.
- [x] Should be able to remove ingredients.
- [x] Should be able to set measurements with the ingredients.

Also, here are a few points that need to be addressed:

1. Constraint 1: 

### Tasks
- [x] Models
- [x] Repository pattern
- [x] Unit of Work pattern
- [x] Controllers
- [x] Entity framework
- [x] Database
- [x] Validation
- [ ] Tests
- [x] Logging
- [x] Comments
