### ISSUE TITLE
Feature: Recipe categorization

### ISSUE THREAD

**Issue by tobinstultiens** [tobinstultiens/Recipe-manager-API#2]
### Description
As a user, I'd like to categorize my recipes, in order to make it easier to find them.

### Acceptance Criteria
Reference: [Done-Done Checklist](https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] Should be able to categorize a recipe.
- [ ] Should be able to create a category.
- [ ] Should be able to remove a category.
- [ ] Should be able to recategorize a recipe.
- [ ] Should be able to remove the category of a recipe.

Also, here are a few points that need to be addressed:

1. Constraint 1: Can only have 1 category at a time.

### Tasks
- [ ] *TBA*
