### ISSUE TITLE
Feature: Recipe tags

### ISSUE THREAD

**Issue by tobinstultiens** [tobinstultiens/Recipe-manager-API#3]
### Description
As a user, I'd like to tag my recipes, in order to make it easy to find them when searching for them.

### Acceptance Criteria
Reference: [Done-Done Checklist](https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] Should be able to add a tag to a recipe.
- [ ] Should be able to add multiple tags to a recipe.
- [ ] Should be able to remove tags from a recipe.
- [ ] Should be able to create tags.
- [ ] Should be able to remove tags.
- [ ] Should be able to change tags.
- [ ] Should be able to select a color for a tag.
- [ ] Should be able to change the color of a tag.

Also, here are a few points that need to be addressed:

1. Constraint 1: A tag can't be longer than 50 words.

### Tasks
- [ ] _TBA_
