### ISSUE TITLE
Feature: Recipe sharing

### ISSUE THREAD

**Issue by tobinstultiens** [tobinstultiens/Recipe-manager-API#4]
### Description
As a user, I'd like to share my recipes, in order to share them between friends and family for them to enjoy.

### Acceptance Criteria
Reference: [Done-Done Checklist](https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] Should be able to post a recipe publicly.
- [ ] Should be able to remove a post.
- [ ] Should be able to edit a post.
- [ ] Should be able to post a recipe between friends.
- [ ] Should be able to post a recipe to a group privately

Also, here are a few points that need to be addressed:

1. Constraint 1: You can only select 1 recipe for posting.
1. Constraint 2: You can only leave a message of 255 characters with the post.
1. Constraint 3: You can share your recipes publicly or between friends.

### Tasks
- [ ] _TBA_
