### ISSUE TITLE
Feature: Friends

### ISSUE THREAD

**Issue by tobinstultiens** [tobinstultiens/Recipe-manager-API#5]
### Description
As a user, I'd like to manage friends, in order to easily share my recipes among them.

### Acceptance Criteria
Reference: [Done-Done Checklist](https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] Should be able to add friends.
- [ ] Should be able to remove friends.
- [ ] Should be able to send my friends posts(related #4).

Also, here are a few points that need to be addressed:

1. Constraint 1:

### Tasks
- [ ] _TBA_
