### ISSUE TITLE
Feature: Groups

### ISSUE THREAD

**Issue by tobinstultiens** [tobinstultiens/Recipe-manager-API#6]
### Description
As a user, I'd like to be able to join and create groups, in order to share my recipes among them specifically.

### Acceptance Criteria
Reference: [Done-Done Checklist](https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] Should be able to add group members.
- [ ] Should be able to remove group members.
- [ ] Should be able to give roles to members.
- [ ] Should be able to leave a group.
- [ ] Should be able to share recipes among them related to #4.

Also, here are a few points that need to be addressed:

1. Constraint 1: You can only have one group owner.
1. Constraint 2: Only the group owner can give other members roles.
1. Constraint 3: Only the group owner is able to give his role to someone else.

### Tasks
- [ ] _TBA_
